application: saturn
version: 1
runtime: python
api_version: 1

handlers:
- url: /static
  static_dir: static

- url: /robots\.txt
  static_files: static/misc/robots.txt
  upload: static/misc/robots.txt

- url: /favicon\.ico
  static_files: static/images/favicon.ico
  upload: static/images/favicon.ico

- url: /god-mode
  script: god-mode.py
  login: admin

- url: /god-mode/.*
  script: god-mode.py
  login: admin

- url: /.*
  script: blog.py
